In [491]:
import sqlite3
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [492]:
database="database.sqlite"

conn=sqlite3.connect(database)

tables=pd.read_sql("""SELECT * FROM sqlite_master WHERE TYPE='table';""",conn)

tables.head(len(tables.values))

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,Player_Attributes,Player_Attributes,11,"CREATE TABLE ""Player_Attributes"" (\n\t`id`\tIN..."
2,table,Player,Player,14,CREATE TABLE `Player` (\n\t`id`\tINTEGER PRIMA...
3,table,Match,Match,18,CREATE TABLE `Match` (\n\t`id`\tINTEGER PRIMAR...
4,table,League,League,24,CREATE TABLE `League` (\n\t`id`\tINTEGER PRIMA...
5,table,Country,Country,26,CREATE TABLE `Country` (\n\t`id`\tINTEGER PRIM...
6,table,Team,Team,29,"CREATE TABLE ""Team"" (\n\t`id`\tINTEGER PRIMARY..."
7,table,Team_Attributes,Team_Attributes,2,CREATE TABLE `Team_Attributes` (\n\t`id`\tINTE...

In [493]:
countries = pd.read_sql("""SELECT *
                        FROM Country;""", conn)

countries.head(len(countries.values))

       id         name
0       1      Belgium
1    1729      England
2    4769       France
3    7809      Germany
4   10257        Italy
5   13274  Netherlands
6   15722       Poland
7   17642     Portugal
8   19694     Scotland
9   21518        Spain
10  24558  Switzerland

In [494]:
leagues = pd.read_sql("""SELECT *
                        FROM League
                        """, conn)
leagues.head(len(leagues.values))

       id  country_id                      name
0       1           1    Belgium Jupiler League
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
3    7809        7809     Germany 1. Bundesliga
4   10257       10257             Italy Serie A
5   13274       13274    Netherlands Eredivisie
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

In [495]:
leagues = pd.read_sql("""SELECT *
                        FROM League
                        JOIN Country ON Country.id = League.country_id;""", conn)
leagues.head(len(leagues.values))

       id  country_id                      name     id         name
0       1           1    Belgium Jupiler League      1      Belgium
1    1729        1729    England Premier League   1729      England
2    4769        4769            France Ligue 1   4769       France
3    7809        7809     Germany 1. Bundesliga   7809      Germany
4   10257       10257             Italy Serie A  10257        Italy
5   13274       13274    Netherlands Eredivisie  13274  Netherlands
6   15722       15722        Poland Ekstraklasa  15722       Poland
7   17642       17642  Portugal Liga ZON Sagres  17642     Portugal
8   19694       19694   Scotland Premier League  19694     Scotland
9   21518       21518           Spain LIGA BBVA  21518        Spain
10  24558       24558  Switzerland Super League  24558  Switzerland

In [496]:
matches=pd.read_sql("""SELECT *
                        FROM Match ORDER BY league_id;""", conn)

#matches.head(len(matches))
matches['possession'].head(10000)

0                                                    None
1                                                    None
2                                                    None
3                                                    None
4                                                    None
5                                                    None
6                                                    None
7                                                    None
8                                                    None
9                                                    None
10                                                   None
11                                                   None
12                                                   None
13                                                   None
14                                                   None
15                                                   None
16                                                   None
17                                                   None
18                                                   None
19                                                   None
20                                                   None
21                                                   None
22                                                   None
23                                                   None
24                                                   None
25                                                   None
26                                                   None
27                                                   None
28                                                   None
29                                                   None
                              ...
9970    <possession><value><comment>46</comment><stats...
9971    <possession><value><comment>62</comment><stats...
9972    <possession><value><comment>70</comment><stats...
9973    <possession><value><comment>34</comment><stats...
9974    <possession><value><comment>27</comment><stats...
9975    <possession><value><comment>52</comment><stats...
9976    <possession><value><comment>37</comment><stats...
9977    <possession><value><comment>67</comment><stats...
9978    <possession><value><comment>65</comment><stats...
9979    <possession><value><comment>55</comment><stats...
9980    <possession><value><comment>54</comment><stats...
9981    <possession><value><comment>57</comment><stats...
9982    <possession><value><comment>41</comment><stats...
9983    <possession><value><comment>45</comment><stats...
9984    <possession><value><comment>24</comment><stats...
9985    <possession><value><comment>45</comment><stats...
9986    <possession><value><comment>32</comment><stats...
9987    <possession><value><comment>52</comment><stats...
9988    <possession><value><comment>65</comment><stats...
9989    <possession><value><comment>42</comment><stats...
9990    <possession><value><comment>49</comment><stats...
9991    <possession><value><comment>24</comment><stats...
9992    <possession><value><comment>47</comment><stats...
9993    <possession><value><comment>57</comment><stats...
9994    <possession><value><comment>53</comment><stats...
9995    <possession><value><comment>71</comment><stats...
9996    <possession><value><comment>68</comment><stats...
9997    <possession><value><comment>53</comment><stats...
9998    <possession><value><comment>40</comment><stats...
9999    <possession><value><comment>43</comment><stats...
Name: possession, Length: 10000, dtype: object

In [497]:
print(matches.columns.values)

['id' 'country_id' 'league_id' 'season' 'stage' 'date' 'match_api_id'
 'home_team_api_id' 'away_team_api_id' 'home_team_goal' 'away_team_goal'
 'home_player_X1' 'home_player_X2' 'home_player_X3' 'home_player_X4'
 'home_player_X5' 'home_player_X6' 'home_player_X7' 'home_player_X8'
 'home_player_X9' 'home_player_X10' 'home_player_X11' 'away_player_X1'
 'away_player_X2' 'away_player_X3' 'away_player_X4' 'away_player_X5'
 'away_player_X6' 'away_player_X7' 'away_player_X8' 'away_player_X9'
 'away_player_X10' 'away_player_X11' 'home_player_Y1' 'home_player_Y2'
 'home_player_Y3' 'home_player_Y4' 'home_player_Y5' 'home_player_Y6'
 'home_player_Y7' 'home_player_Y8' 'home_player_Y9' 'home_player_Y10'
 'home_player_Y11' 'away_player_Y1' 'away_player_Y2' 'away_player_Y3'
 'away_player_Y4' 'away_player_Y5' 'away_player_Y6' 'away_player_Y7'
 'away_player_Y8' 'away_player_Y9' 'away_player_Y10' 'away_player_Y11'
 'home_player_1' 'home_player_2' 'home_player_3' 'home_player_4'
 'home_player_5' 'home_player_6' 'home_player_7' 'home_player_8'
 'home_player_9' 'home_player_10' 'home_player_11' 'away_player_1'
 'away_player_2' 'away_player_3' 'away_player_4' 'away_player_5'
 'away_player_6' 'away_player_7' 'away_player_8' 'away_player_9'
 'away_player_10' 'away_player_11' 'goal' 'shoton' 'shotoff' 'foulcommit'
 'card' 'cross' 'corner' 'possession' 'B365H' 'B365D' 'B365A' 'BWH' 'BWD'
 'BWA' 'IWH' 'IWD' 'IWA' 'LBH' 'LBD' 'LBA' 'PSH' 'PSD' 'PSA' 'WHH' 'WHD'
 'WHA' 'SJH' 'SJD' 'SJA' 'VCH' 'VCD' 'VCA' 'GBH' 'GBD' 'GBA' 'BSH' 'BSD'
 'BSA']

In [498]:
detailed_matches = pd.read_sql("""SELECT Match.id, 
                                        Country.name AS country_name, 
                                        League.name AS league_name, 
                                        season, 
                                        stage, 
                                        date,
                                        HT.team_long_name AS  home_team,
                                        AT.team_long_name AS away_team,
                                        home_team_goal, 
                                        away_team_goal                                        
                                FROM Match
                                JOIN Country on Country.id = Match.country_id
                                JOIN League on League.id = Match.league_id
                                LEFT JOIN Team AS HT on HT.team_api_id = Match.home_team_api_id
                                LEFT JOIN Team AS AT on AT.team_api_id = Match.away_team_api_id
                                ;""" ,conn)
detailed_matches=pd.DataFrame(detailed_matches).set_index('id')

detailed_matches.head(len(detailed_matches.values))

,country_name,league_name,season,stage,date,home_team,away_team,home_team_goal,away_team_goal
id,,,,,,,,,
1,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-17 00:00:00,KRC Genk,Beerschot AC,1,1
2,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16 00:00:00,SV Zulte-Waregem,Sporting Lokeren,0,0
3,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16 00:00:00,KSV Cercle Brugge,RSC Anderlecht,0,3
4,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-17 00:00:00,KAA Gent,RAEC Mons,5,0
5,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16 00:00:00,FCV Dender EH,Standard de Liège,1,3
6,Belgium,Belgium Jupiler League,2008/2009,1,2008-09-24 00:00:00,KV Mechelen,Club Brugge KV,1,1
7,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16 00:00:00,KSV Roeselare,KV Kortrijk,2,2
8,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16 00:00:00,Tubize,Royal Excel Mouscron,1,2
9,Belgium,Belgium Jupiler League,2008/2009,1,2008-08-16 00:00:00,KVC Westerlo,Sporting Charleroi,1,0
10,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01 00:00:00,Club Brugge KV,KV Kortrijk,4,1
11,Belgium,Belgium Jupiler League,2008/2009,10,2008-10-31 00:00:00,Standard de Liège,Sporting Charleroi,1,2
12,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-02 00:00:00,SV Zulte-Waregem,KAA Gent,0,2
13,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01 00:00:00,Sporting Lokeren,RAEC Mons,0,0
14,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01 00:00:00,FCV Dender EH,KVC Westerlo,2,2
15,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01 00:00:00,KV Mechelen,KSV Roeselare,1,2
16,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01 00:00:00,Royal Excel Mouscron,KSV Cercle Brugge,0,1
17,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-01 00:00:00,Tubize,KRC Genk,1,3
18,Belgium,Belgium Jupiler League,2008/2009,10,2008-11-02 00:00:00,Beerschot AC,RSC Anderlecht,1,3
19,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08 00:00:00,RSC Anderlecht,Sporting Lokeren,2,3
20,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08 00:00:00,RAEC Mons,Royal Excel Mouscron,0,0
21,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-09 00:00:00,Sporting Charleroi,Club Brugge KV,2,2
22,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-07 00:00:00,KSV Cercle Brugge,SV Zulte-Waregem,2,0
23,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08 00:00:00,KAA Gent,FCV Dender EH,1,1
24,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08 00:00:00,KSV Roeselare,Tubize,1,2
25,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08 00:00:00,KV Kortrijk,KV Mechelen,0,0
26,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-08 00:00:00,KVC Westerlo,KRC Genk,1,0
27,Belgium,Belgium Jupiler League,2008/2009,11,2008-11-09 00:00:00,Beerschot AC,Standard de Liège,1,3
28,Belgium,Belgium Jupiler League,2008/2009,12,2008-11-16 00:00:00,Club Brugge KV,RSC Anderlecht,1,1
29,Belgium,Belgium Jupiler League,2008/2009,12,2008-11-15 00:00:00,KRC Genk,KSV Roeselare,1,1
30,Belgium,Belgium Jupiler League,2008/2009,12,2008-11-15 00:00:00,SV Zulte-Waregem,Beerschot AC,2,2
...,...,...,...,...,...,...,...,...,...
25950,Switzerland,Switzerland Super League,2015/2016,4,2015-08-08 00:00:00,Grasshopper Club Zürich,Lugano,6,1
25951,Switzerland,Switzerland Super League,2015/2016,4,2015-08-08 00:00:00,FC Luzern,FC Basel,1,3
25952,Switzerland,Switzerland Super League,2015/2016,4,2015-08-09 00:00:00,FC St. Gallen,FC Zürich,0,2
25953,Switzerland,Switzerland Super League,2015/2016,4,2015-08-09 00:00:00,FC Vaduz,FC Sion,1,1
25954,Switzerland,Switzerland Super League,2015/2016,4,2015-08-09 00:00:00,BSC Young Boys,FC Thun,3,1
25955,Switzerland,Switzerland Super League,2015/2016,5,2015-08-12 00:00:00,FC Basel,FC Thun,3,1
25956,Switzerland,Switzerland Super League,2015/2016,5,2015-08-12 00:00:00,BSC Young Boys,Lugano,0,1
25957,Switzerland,Switzerland Super League,2015/2016,5,2015-08-12 00:00:00,FC Luzern,FC St. Gallen,0,1
25958,Switzerland,Switzerland Super League,2015/2016,5,2015-08-13 00:00:00,FC Sion,FC Zürich,3,1
25959,Switzerland,Switzerland Super League,2015/2016,5,2015-08-13 00:00:00,FC Vaduz,Grasshopper Club Zürich,3,3
25960,Switzerland,Switzerland Super League,2015/2016,6,2015-08-22 00:00:00,Lugano,FC Basel,1,3
25961,Switzerland,Switzerland Super League,2015/2016,6,2015-08-23 00:00:00,FC Sion,BSC Young Boys,1,3
25962,Switzerland,Switzerland Super League,2015/2016,6,2015-08-23 00:00:00,FC St. Gallen,Grasshopper Club Zürich,0,2
25963,Switzerland,Switzerland Super League,2015/2016,6,2015-08-23 00:00:00,FC Thun,FC Vaduz,1,0
25964,Switzerland,Switzerland Super League,2015/2016,6,2015-08-22 00:00:00,FC Zürich,FC Luzern,2,5
25965,Switzerland,Switzerland Super League,2015/2016,7,2015-08-29 00:00:00,Lugano,FC Luzern,0,1
25966,Switzerland,Switzerland Super League,2015/2016,7,2015-08-29 00:00:00,FC Vaduz,FC St. Gallen,1,0
25967,Switzerland,Switzerland Super League,2015/2016,7,2015-08-30 00:00:00,FC Thun,FC Sion,0,2
25968,Switzerland,Switzerland Super League,2015/2016,7,2015-08-30 00:00:00,FC Basel,FC Zürich,3,1
25969,Switzerland,Switzerland Super League,2015/2016,7,2015-08-30 00:00:00,Grasshopper Club Zürich,BSC Young Boys,3,2
25970,Switzerland,Switzerland Super League,2015/2016,8,2015-09-12 00:00:00,FC Basel,FC St. Gallen,2,1
25971,Switzerland,Switzerland Super League,2015/2016,8,2015-09-12 00:00:00,BSC Young Boys,FC Vaduz,4,0
25972,Switzerland,Switzerland Super League,2015/2016,8,2015-09-13 00:00:00,FC Luzern,Grasshopper Club Zürich,3,3
25973,Switzerland,Switzerland Super League,2015/2016,8,2015-09-13 00:00:00,FC Zürich,FC Thun,3,3
25974,Switzerland,Switzerland Super League,2015/2016,8,2015-09-13 00:00:00,FC Sion,Lugano,3,0
25975,Switzerland,Switzerland Super League,2015/2016,9,2015-09-22 00:00:00,FC St. Gallen,FC Thun,1,0
25976,Switzerland,Switzerland Super League,2015/2016,9,2015-09-23 00:00:00,FC Vaduz,FC Luzern,1,2
25977,Switzerland,Switzerland Super League,2015/2016,9,2015-09-23 00:00:00,Grasshopper Club Zürich,FC Sion,2,0
25978,Switzerland,Switzerland Super League,2015/2016,9,2015-09-22 00:00:00,Lugano,FC Zürich,0,0
25979,Switzerland,Switzerland Super League,2015/2016,9,2015-09-23 00:00:00,BSC Young Boys,FC Basel,4,3

In [499]:
categorical=['object']
categorical_data=matches.select_dtypes(categorical)
print(categorical_data.columns)
categorical_data.isnull().sum()
categorical_data.head()

Index(['season', 'date', 'goal', 'shoton', 'shotoff', 'foulcommit', 'card',
       'cross', 'corner', 'possession'],
      dtype='object')

,season,date,goal,shoton,shotoff,foulcommit,card,cross,corner,possession
0,2008/2009,2008-08-17 00:00:00,None,None,None,None,None,None,None,None
1,2008/2009,2008-08-16 00:00:00,None,None,None,None,None,None,None,None
2,2008/2009,2008-08-16 00:00:00,None,None,None,None,None,None,None,None
3,2008/2009,2008-08-17 00:00:00,None,None,None,None,None,None,None,None
4,2008/2009,2008-08-16 00:00:00,None,None,None,None,None,None,None,None

In [500]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
numeric_columns=matches.select_dtypes(numerics)
print(numeric_columns.columns.values)

['id' 'country_id' 'league_id' 'stage' 'match_api_id' 'home_team_api_id'
 'away_team_api_id' 'home_team_goal' 'away_team_goal' 'home_player_X1'
 'home_player_X2' 'home_player_X3' 'home_player_X4' 'home_player_X5'
 'home_player_X6' 'home_player_X7' 'home_player_X8' 'home_player_X9'
 'home_player_X10' 'home_player_X11' 'away_player_X1' 'away_player_X2'
 'away_player_X3' 'away_player_X4' 'away_player_X5' 'away_player_X6'
 'away_player_X7' 'away_player_X8' 'away_player_X9' 'away_player_X10'
 'away_player_X11' 'home_player_Y1' 'home_player_Y2' 'home_player_Y3'
 'home_player_Y4' 'home_player_Y5' 'home_player_Y6' 'home_player_Y7'
 'home_player_Y8' 'home_player_Y9' 'home_player_Y10' 'home_player_Y11'
 'away_player_Y1' 'away_player_Y2' 'away_player_Y3' 'away_player_Y4'
 'away_player_Y5' 'away_player_Y6' 'away_player_Y7' 'away_player_Y8'
 'away_player_Y9' 'away_player_Y10' 'away_player_Y11' 'home_player_1'
 'home_player_2' 'home_player_3' 'home_player_4' 'home_player_5'
 'home_player_6' 'home_player_7' 'home_player_8' 'home_player_9'
 'home_player_10' 'home_player_11' 'away_player_1' 'away_player_2'
 'away_player_3' 'away_player_4' 'away_player_5' 'away_player_6'
 'away_player_7' 'away_player_8' 'away_player_9' 'away_player_10'
 'away_player_11' 'B365H' 'B365D' 'B365A' 'BWH' 'BWD' 'BWA' 'IWH' 'IWD'
 'IWA' 'LBH' 'LBD' 'LBA' 'PSH' 'PSD' 'PSA' 'WHH' 'WHD' 'WHA' 'SJH' 'SJD'
 'SJA' 'VCH' 'VCD' 'VCA' 'GBH' 'GBD' 'GBA' 'BSH' 'BSD' 'BSA']

In [501]:
numeric_columns.isnull().sum()

id                      0
country_id              0
league_id               0
stage                   0
match_api_id            0
home_team_api_id        0
away_team_api_id        0
home_team_goal          0
away_team_goal          0
home_player_X1       1821
home_player_X2       1821
home_player_X3       1832
home_player_X4       1832
home_player_X5       1832
home_player_X6       1832
home_player_X7       1832
home_player_X8       1832
home_player_X9       1832
home_player_X10      1832
home_player_X11      1832
away_player_X1       1832
away_player_X2       1832
away_player_X3       1832
away_player_X4       1832
away_player_X5       1832
away_player_X6       1832
away_player_X7       1832
away_player_X8       1832
away_player_X9       1833
away_player_X10      1833
                    ...
B365H                3387
B365D                3387
B365A                3387
BWH                  3404
BWD                  3404
BWA                  3404
IWH                  3459
IWD                  3459
IWA                  3459
LBH                  3423
LBD                  3423
LBA                  3423
PSH                 14811
PSD                 14811
PSA                 14811
WHH                  3408
WHD                  3408
WHA                  3408
SJH                  8882
SJD                  8882
SJA                  8882
VCH                  3411
VCD                  3411
VCA                  3411
GBH                 11817
GBD                 11817
GBA                 11817
BSH                 11818
BSD                 11818
BSA                 11818
Length: 105, dtype: int64

In [502]:
detailed_matches.isnull().sum()

country_name      0
league_name       0
season            0
stage             0
date              0
home_team         0
away_team         0
home_team_goal    0
away_team_goal    0
dtype: int64

In [503]:
matches.isnull().sum()

id                      0
country_id              0
league_id               0
season                  0
stage                   0
date                    0
match_api_id            0
home_team_api_id        0
away_team_api_id        0
home_team_goal          0
away_team_goal          0
home_player_X1       1821
home_player_X2       1821
home_player_X3       1832
home_player_X4       1832
home_player_X5       1832
home_player_X6       1832
home_player_X7       1832
home_player_X8       1832
home_player_X9       1832
home_player_X10      1832
home_player_X11      1832
away_player_X1       1832
away_player_X2       1832
away_player_X3       1832
away_player_X4       1832
away_player_X5       1832
away_player_X6       1832
away_player_X7       1832
away_player_X8       1832
                    ...
B365H                3387
B365D                3387
B365A                3387
BWH                  3404
BWD                  3404
BWA                  3404
IWH                  3459
IWD                  3459
IWA                  3459
LBH                  3423
LBD                  3423
LBA                  3423
PSH                 14811
PSD                 14811
PSA                 14811
WHH                  3408
WHD                  3408
WHA                  3408
SJH                  8882
SJD                  8882
SJA                  8882
VCH                  3411
VCD                  3411
VCA                  3411
GBH                 11817
GBD                 11817
GBA                 11817
BSH                 11818
BSD                 11818
BSA                 11818
Length: 115, dtype: int64

In [504]:
teams=pd.read_sql("""SELECT *
                        FROM Team;""",conn)

teams.head(len(teams.values))

,id,team_api_id,team_fifa_api_id,team_long_name,team_short_name
0,1,9987,673.0,KRC Genk,GEN
1,2,9993,675.0,Beerschot AC,BAC
2,3,10000,15005.0,SV Zulte-Waregem,ZUL
3,4,9994,2007.0,Sporting Lokeren,LOK
4,5,9984,1750.0,KSV Cercle Brugge,CEB
5,6,8635,229.0,RSC Anderlecht,AND
6,7,9991,674.0,KAA Gent,GEN
7,8,9998,1747.0,RAEC Mons,MON
8,9,7947,NaN,FCV Dender EH,DEN
9,10,9985,232.0,Standard de Liège,STL
10,11,8203,110724.0,KV Mechelen,MEC
11,12,8342,231.0,Club Brugge KV,CLB
12,13,9999,546.0,KSV Roeselare,ROS
13,14,8571,100081.0,KV Kortrijk,KOR
14,15,4049,NaN,Tubize,TUB
15,16,9996,111560.0,Royal Excel Mouscron,MOU
16,17,10001,681.0,KVC Westerlo,WES
17,18,9986,670.0,Sporting Charleroi,CHA
18,614,9997,680.0,Sint-Truidense VV,STT
19,1034,9989,239.0,Lierse SK,LIE
20,1042,6351,2013.0,KAS Eupen,EUP
21,1513,1773,100087.0,Oud-Heverlee Leuven,O-H
22,2004,8475,110913.0,Waasland-Beveren,WAA
23,2476,8573,682.0,KV Oostende,OOS
24,2510,274581,111560.0,Royal Excel Mouscron,MOP
25,3457,10260,11.0,Manchester United,MUN
26,3458,10261,13.0,Newcastle United,NEW
27,3459,9825,1.0,Arsenal,ARS
28,3460,8659,109.0,West Bromwich Albion,WBA
29,3461,8472,106.0,Sunderland,SUN
...,...,...,...,...,...
269,43053,9906,240.0,Atlético Madrid,AMA
270,43054,9864,573.0,Málaga CF,MAL
271,43800,9868,1742.0,Xerez Club Deportivo,XER
272,43803,8394,244.0,Real Zaragoza,ZAR
273,43804,9867,260.0,CD Tenerife,TEN
274,44557,10278,100879.0,Hércules Club de Fútbol,HER
275,44565,8581,1853.0,Levante UD,LEV
276,44569,8560,457.0,Real Sociedad,SOC
277,45330,7878,110832.0,Granada CF,GRA
278,45333,8370,480.0,Rayo Vallecano,RAY
279,46087,9910,450.0,RC Celta de Vigo,CEL
280,46848,10268,468.0,Elche CF,ELC
281,47605,8372,467.0,SD Eibar,EIB
282,47612,7869,1867.0,Córdoba CF,COR
283,48358,8306,472.0,UD Las Palmas,LAS
284,49115,9956,322.0,Grasshopper Club Zürich,GRA
285,49116,6493,1714.0,AC Bellinzona,BEL
286,49117,10192,900.0,BSC Young Boys,YB
287,49118,9931,896.0,FC Basel,BAS
288,49119,9930,434.0,FC Aarau,AAR
289,49120,10179,110770.0,FC Sion,SIO
290,49121,10199,897.0,FC Luzern,LUZ
291,49122,9824,286.0,FC Vaduz,VAD
292,49123,7955,435.0,Neuchâtel Xamax,XAM
293,49124,10243,894.0,FC Zürich,ZUR
294,49479,10190,898.0,FC St. Gallen,GAL
295,49837,10191,1715.0,FC Thun,THU
296,50201,9777,324.0,Servette FC,SER
297,50204,7730,1862.0,FC Lausanne-Sports,LAU
298,51606,7896,NaN,Lugano,LUG

In [505]:
players = pd.read_sql("SELECT * FROM Player;",conn)
players.isnull().sum()

id                    0
player_api_id         0
player_name           0
player_fifa_api_id    0
birthday              0
height                0
weight                0
dtype: int64

In [507]:
players_stats = pd.read_sql("SELECT * FROM Player_Attributes",conn)
players_stats.isnull().sum()

id                        0
player_fifa_api_id        0
player_api_id             0
date                      0
overall_rating          836
potential               836
preferred_foot          836
attacking_work_rate    3230
defensive_work_rate     836
crossing                836
finishing               836
heading_accuracy        836
short_passing           836
volleys                2713
dribbling               836
curve                  2713
free_kick_accuracy      836
long_passing            836
ball_control            836
acceleration            836
sprint_speed            836
agility                2713
reactions               836
balance                2713
shot_power              836
jumping                2713
stamina                 836
strength                836
long_shots              836
aggression              836
interceptions           836
positioning             836
vision                 2713
penalties               836
marking                 836
standing_tackle         836
sliding_tackle         2713
gk_diving               836
gk_handling             836
gk_kicking              836
gk_positioning          836
gk_reflexes             836
dtype: int64

In [508]:
players_stats.head(len(players_stats.values))

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
5,6,189615,155782,2016-04-21 00:00:00,74.0,76.0,left,high,medium,80.0,...,66.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
6,7,189615,155782,2016-04-07 00:00:00,74.0,76.0,left,high,medium,80.0,...,66.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
7,8,189615,155782,2016-01-07 00:00:00,73.0,75.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
8,9,189615,155782,2015-12-24 00:00:00,73.0,75.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
9,10,189615,155782,2015-12-17 00:00:00,73.0,75.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
10,11,189615,155782,2015-10-16 00:00:00,73.0,77.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
11,12,189615,155782,2015-09-25 00:00:00,74.0,78.0,left,high,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
12,13,189615,155782,2015-09-21 00:00:00,73.0,77.0,left,medium,medium,79.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
13,14,189615,155782,2015-01-09 00:00:00,71.0,75.0,left,medium,medium,78.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
14,15,189615,155782,2014-12-05 00:00:00,71.0,77.0,left,medium,medium,78.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
15,16,189615,155782,2014-11-07 00:00:00,71.0,77.0,left,medium,medium,78.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
16,17,189615,155782,2014-09-18 00:00:00,70.0,77.0,left,medium,medium,77.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
17,18,189615,155782,2014-05-02 00:00:00,70.0,79.0,left,medium,medium,77.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
18,19,189615,155782,2014-04-04 00:00:00,70.0,79.0,left,medium,medium,77.0,...,64.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
19,20,189615,155782,2014-03-14 00:00:00,70.0,79.0,left,medium,medium,77.0,...,61.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
20,21,189615,155782,2013-12-13 00:00:00,70.0,79.0,left,medium,medium,77.0,...,61.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
21,22,189615,155782,2013-11-08 00:00:00,70.0,79.0,left,medium,medium,77.0,...,61.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
22,23,189615,155782,2013-10-04 00:00:00,69.0,79.0,left,medium,medium,77.0,...,58.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
23,24,189615,155782,2013-09-20 00:00:00,69.0,79.0,left,medium,medium,77.0,...,58.0,58.0,73.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
24,25,189615,155782,2013-05-03 00:00:00,69.0,80.0,left,medium,medium,77.0,...,58.0,58.0,72.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
25,26,189615,155782,2013-03-22 00:00:00,69.0,80.0,left,medium,medium,77.0,...,58.0,58.0,72.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
26,27,189615,155782,2013-03-15 00:00:00,69.0,80.0,left,medium,medium,77.0,...,58.0,58.0,72.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
27,28,189615,155782,2013-02-22 00:00:00,69.0,80.0,left,medium,medium,77.0,...,58.0,58.0,72.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
28,29,189615,155782,2013-02-15 00:00:00,69.0,80.0,left,medium,medium,77.0,...,58.0,58.0,72.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
29,30,189615,155782,2012-08-31 00:00:00,68.0,80.0,left,medium,medium,77.0,...,63.0,58.0,72.0,72.0,72.0,13.0,6.0,8.0,8.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183948,183949,164680,111182,2012-02-22 00:00:00,68.0,76.0,left,medium,medium,73.0,...,45.0,53.0,64.0,68.0,66.0,9.0,8.0,5.0,5.0,8.0
183949,183950,164680,111182,2011-08-30 00:00:00,68.0,76.0,left,medium,medium,73.0,...,45.0,53.0,64.0,68.0,66.0,9.0,8.0,5.0,5.0,8.0
183950,183951,164680,111182,2011-02-22 00:00:00,68.0,79.0,left,medium,medium,71.0,...,65.0,53.0,71.0,69.0,69.0,9.0,8.0,5.0,5.0,8.0
183951,183952,164680,111182,2010-08-30 00:00:00,67.0,77.0,left,medium,medium,68.0,...,65.0,44.0,75.0,70.0,67.0,9.0,8.0,5.0,5.0,8.0
183952,183953,164680,111182,2007-02-22 00:00:00,67.0,77.0,left,medium,medium,68.0,...,65.0,44.0,75.0,70.0,67.0,9.0,8.0,5.0,5.0,8.0
183953,183954,111191,36491,2011-02-22 00:00:00,68.0,73.0,left,None,_0,64.0,...,66.0,61.0,67.0,71.0,59.0,15.0,13.0,5.0,6.0,6.0
183954,183955,111191,36491,2010-08-30 00:00:00,68.0,73.0,left,None,_0,64.0,...,66.0,61.0,71.0,71.0,59.0,15.0,13.0,5.0,6.0,6.0
183955,183956,111191,36491,2009-08-30 00:00:00,68.0,74.0,left,None,_0,64.0,...,66.0,61.0,71.0,71.0,59.0,4.0,21.0,61.0,21.0,21.0
183956,183957,111191,36491,2009-02-22 00:00:00,68.0,74.0,left,None,_0,64.0,...,66.0,61.0,71.0,71.0,59.0,4.0,21.0,61.0,21.0,21.0
183957,183958,111191,36491,2008-08-30 00:00:00,67.0,72.0,left,None,_0,62.0,...,66.0,61.0,61.0,62.0,59.0,4.0,21.0,61.0,21.0,21.0
183958,183959,111191,36491,2007-08-30 00:00:00,67.0,72.0,left,None,_0,62.0,...,66.0,61.0,43.0,52.0,59.0,4.0,21.0,52.0,21.0,21.0
183959,183960,111191,36491,2007-02-22 00:00:00,67.0,72.0,left,None,_0,62.0,...,66.0,61.0,43.0,52.0,59.0,4.0,21.0,52.0,21.0,21.0
183960,183961,47058,35506,2011-02-22 00:00:00,67.0,78.0,right,None,_0,48.0,...,63.0,45.0,65.0,66.0,65.0,14.0,7.0,15.0,10.0,12.0
183961,183962,47058,35506,2010-08-30 00:00:00,67.0,78.0,right,None,_0,48.0,...,63.0,45.0,65.0,66.0,65.0,14.0,7.0,15.0,10.0,12.0
183962,183963,47058,35506,2010-02-22 00:00:00,67.0,78.0,right,None,_0,48.0,...,63.0,70.0,65.0,66.0,65.0,14.0,25.0,51.0,25.0,25.0
183963,183964,47058,35506,2009-08-30 00:00:00,70.0,78.0,right,None,_0,48.0,...,63.0,70.0,70.0,74.0,65.0,14.0,25.0,51.0,25.0,25.0
183964,183965,47058,35506,2009-02-22 00:00:00,70.0,78.0,right,None,_0,48.0,...,63.0,70.0,70.0,74.0,65.0,14.0,25.0,51.0,25.0,25.0
183965,183966,47058,35506,2008-08-30 00:00:00,72.0,78.0,right,None,_0,48.0,...,63.0,70.0,76.0,78.0,65.0,14.0,25.0,51.0,25.0,25.0
183966,183967,47058,35506,2007-08-30 00:00:00,75.0,78.0,right,None,_0,48.0,...,63.0,70.0,76.0,78.0,65.0,14.0,25.0,51.0,25.0,25.0
183967,183968,47058,35506,2007-02-22 00:00:00,78.0,79.0,right,None,_0,38.0,...,63.0,72.0,79.0,84.0,65.0,14.0,9.0,48.0,7.0,11.0
183968,183969,102359,39902,2012-08-31 00:00:00,78.0,78.0,right,medium,low,77.0,...,82.0,78.0,22.0,31.0,30.0,9.0,13.0,8.0,15.0,5.0
183969,183970,102359,39902,2012-02-22 00:00:00,81.0,81.0,right,medium,low,80.0,...,87.0,78.0,22.0,31.0,30.0,9.0,13.0,8.0,15.0,5.0
183970,183971,102359,39902,2011-08-30 00:00:00,81.0,81.0,right,medium,low,80.0,...,87.0,78.0,22.0,31.0,30.0,9.0,13.0,8.0,15.0,5.0
183971,183972,102359,39902,2011-02-22 00:00:00,81.0,85.0,right,medium,low,81.0,...,87.0,73.0,22.0,31.0,30.0,9.0,13.0,8.0,15.0,5.0
183972,183973,102359,39902,2010-08-30 00:00:00,83.0,85.0,right,medium,low,84.0,...,88.0,73.0,22.0,31.0,30.0,9.0,13.0,8.0,15.0,5.0
183973,183974,102359,39902,2009-08-30 00:00:00,83.0,85.0,right,medium,low,84.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183975,102359,39902,2009-02-22 00:00:00,78.0,80.0,right,medium,low,74.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183976,102359,39902,2008-08-30 00:00:00,77.0,80.0,right,medium,low,74.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183977,102359,39902,2007-08-30 00:00:00,78.0,81.0,right,medium,low,74.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183978,102359,39902,2007-02-22 00:00:00,80.0,81.0,right,medium,low,74.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

In [511]:
matches.isnull().sum()

id                      0
country_id              0
league_id               0
season                  0
stage                   0
date                    0
match_api_id            0
home_team_api_id        0
away_team_api_id        0
home_team_goal          0
away_team_goal          0
home_player_X1       1821
home_player_X2       1821
home_player_X3       1832
home_player_X4       1832
home_player_X5       1832
home_player_X6       1832
home_player_X7       1832
home_player_X8       1832
home_player_X9       1832
home_player_X10      1832
home_player_X11      1832
away_player_X1       1832
away_player_X2       1832
away_player_X3       1832
away_player_X4       1832
away_player_X5       1832
away_player_X6       1832
away_player_X7       1832
away_player_X8       1832
                    ...
B365H                3387
B365D                3387
B365A                3387
BWH                  3404
BWD                  3404
BWA                  3404
IWH                  3459
IWD                  3459
IWA                  3459
LBH                  3423
LBD                  3423
LBA                  3423
PSH                 14811
PSD                 14811
PSA                 14811
WHH                  3408
WHD                  3408
WHA                  3408
SJH                  8882
SJD                  8882
SJA                  8882
VCH                  3411
VCD                  3411
VCA                  3411
GBH                 11817
GBD                 11817
GBA                 11817
BSH                 11818
BSD                 11818
BSA                 11818
Length: 115, dtype: int64

In [512]:
matches.dropna(inplace = True)
print(matches.isnull().sum())

id                  0
country_id          0
league_id           0
season              0
stage               0
date                0
match_api_id        0
home_team_api_id    0
away_team_api_id    0
home_team_goal      0
away_team_goal      0
home_player_X1      0
home_player_X2      0
home_player_X3      0
home_player_X4      0
home_player_X5      0
home_player_X6      0
home_player_X7      0
home_player_X8      0
home_player_X9      0
home_player_X10     0
home_player_X11     0
away_player_X1      0
away_player_X2      0
away_player_X3      0
away_player_X4      0
away_player_X5      0
away_player_X6      0
away_player_X7      0
away_player_X8      0
                   ..
B365H               0
B365D               0
B365A               0
BWH                 0
BWD                 0
BWA                 0
IWH                 0
IWD                 0
IWA                 0
LBH                 0
LBD                 0
LBA                 0
PSH                 0
PSD                 0
PSA                 0
WHH                 0
WHD                 0
WHA                 0
SJH                 0
SJD                 0
SJA                 0
VCH                 0
VCD                 0
VCA                 0
GBH                 0
GBD                 0
GBA                 0
BSH                 0
BSD                 0
BSA                 0
Length: 115, dtype: int64

In [513]:
def get_outcome(matches):
    home_goals = matches['home_team_goal']
    away_goals = matches['away_team_goal']
    
    outcome = pd.DataFrame()
    outcome.loc[0,'match_api_id'] = matches['match_api_id']
    
    if home_goals > away_goals:
        outcome.loc[0,'outcome'] = "Win"
    if home_goals == away_goals:
        outcome.loc[0,'outcome'] = "Draw"
    if home_goals < away_goals:
        outcome.loc[0,'outcome'] = "Lost"
      
    return outcome.loc[0]

In [515]:
def get_last_matches(matches, date, team, x = 20):
    
    team_matches = matches[(matches['home_team_api_id'] == team) | (matches['away_team_api_id'] == team)]
                           
    last_matches = team_matches[team_matches.date < date].sort_values(by = 'date', ascending = False).iloc[0:x,:]
    
    return last_matches

In [516]:
def get_last_matches_against_eachother(matches, date, home_team, away_team, x = 20):
    
    home_matches = matches[(matches['home_team_api_id'] == home_team) & (matches['away_team_api_id'] == away_team)]    
    away_matches = matches[(matches['home_team_api_id'] == away_team) & (matches['away_team_api_id'] == home_team)]  
    total_matches = pd.concat([home_matches, away_matches])

    try:    
        last_matches = total_matches[total_matches.date < date].sort_values(by = 'date', ascending = False).iloc[0:x,:]
    except:
        last_matches = total_matches[total_matches.date < date].sort_values(by = 'date', ascending = False).iloc[0:total_matches.shape[0],:]
        
        if(last_matches.shape[0] > x):
            print("Error in obtaining matches")
            
    return last_matches

In [517]:
def get_goals(matches, team):
    
    home_goals = int(matches.home_team_goal[matches.home_team_api_id == team].sum())
    away_goals = int(matches.away_team_goal[matches.away_team_api_id == team].sum())

    total_goals = home_goals + away_goals

    return total_goals

In [518]:
def get_goals_conceided(matches, team):

    home_goals = int(matches.home_team_goal[matches.away_team_api_id == team].sum())
    away_goals = int(matches.away_team_goal[matches.home_team_api_id == team].sum())

    total_goals = home_goals + away_goals

    return total_goals

In [519]:
def get_wins(matches, team):
    
    home_wins = int(matches.home_team_goal[(matches.home_team_api_id == team) & (matches.home_team_goal > matches.away_team_goal)].count())
    away_wins = int(matches.away_team_goal[(matches.away_team_api_id == team) & (matches.away_team_goal > matches.home_team_goal)].count())

    total_wins = home_wins + away_wins

    return total_wins

In [520]:
def get_match_features(match, matches, x = 10):
    
    
    date = match.date
    home_team = match.home_team_api_id
    away_team = match.away_team_api_id
    
    
    matches_home_team = get_last_matches(matches, date, home_team, x = 10)
    matches_away_team = get_last_matches(matches, date, away_team, x = 10)
    
    
    last_matches_against = get_last_matches_against_eachother(matches, date, home_team, away_team, x = 3)
    
 
    home_goals = get_goals(matches_home_team, home_team)
    away_goals = get_goals(matches_away_team, away_team)
    home_goals_conceided = get_goals_conceided(matches_home_team, home_team)
    away_goals_conceided = get_goals_conceided(matches_away_team, away_team)
    
 
    result = pd.DataFrame()
    

    result.loc[0, 'match_api_id'] = match.match_api_id
    result.loc[0, 'league_id'] = match.league_id


    result.loc[0, 'home_team_goals_difference'] = home_goals - home_goals_conceided
    result.loc[0, 'away_team_goals_difference'] = away_goals - away_goals_conceided
    result.loc[0, 'games_won_home_team'] = get_wins(matches_home_team, home_team) 
    result.loc[0, 'games_won_away_team'] = get_wins(matches_away_team, away_team)
    result.loc[0, 'games_against_won'] = get_wins(last_matches_against, home_team)
    result.loc[0, 'games_against_lost'] = get_wins(last_matches_against, away_team)
    

    return result.loc[0]

In [521]:
matches.head(len(matches.values))
rows = ["country_id", "league_id", "season", "stage", "date", "match_api_id", "home_team_api_id", 
        "away_team_api_id", "home_team_goal", "away_team_goal", "home_player_1", "home_player_2",
        "home_player_3", "home_player_4", "home_player_5", "home_player_6", "home_player_7", 
        "home_player_8", "home_player_9", "home_player_10", "home_player_11", "away_player_1",
        "away_player_2", "away_player_3", "away_player_4", "away_player_5", "away_player_6",
        "away_player_7", "away_player_8", "away_player_9", "away_player_10", "away_player_11","goal",
        "shoton","shotoff","foulcommit","card","cross","corner","possession"]
matches.dropna(subset = rows, inplace = True)

matches = matches.drop(["B365H","B365D","B365A","BWH","BWD","BWA","IWH","IWD",
                        "IWA","LBH","LBD","LBA","PSH","PSD","PSA","WHH","WHD","WHA","SJH","SJD" 
                        ,"SJA","VCH","VCD","VCA","GBH","GBD","GBA","BSH","BSD","BSA"], axis=1)

In [522]:
from matplotlib import pyplot as plt

In [572]:
import seaborn as sb
corr_matrix = matches.corr(method = 'pearson')
corr_matrix

,id,country_id,league_id,stage,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,...,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,match_api_id
id,1.000000,0.999723,0.999723,0.019283,0.572916,-0.155162,-0.161508,0.045331,-0.011853,NaN,...,0.142171,0.173814,0.017084,0.077242,0.188901,0.075846,0.117966,0.118446,0.053210,0.572916
country_id,0.999723,1.000000,1.000000,0.015060,0.572730,-0.155637,-0.161867,0.045875,-0.010921,NaN,...,0.142568,0.174333,0.018041,0.076641,0.188922,0.078047,0.118706,0.120215,0.054280,0.572730
league_id,0.999723,1.000000,1.000000,0.015060,0.572730,-0.155637,-0.161867,0.045875,-0.010921,NaN,...,0.142568,0.174333,0.018041,0.076641,0.188922,0.078047,0.118706,0.120215,0.054280,0.572730
stage,0.019283,0.015060,0.015060,1.000000,0.022703,0.023674,0.022605,-0.020307,0.012219,NaN,...,0.016421,0.045897,0.087980,0.068206,0.022223,0.023593,0.028204,0.083800,0.023077,0.022703
match_api_id,0.572916,0.572730,0.572730,0.022703,1.000000,-0.089011,-0.098556,0.017903,-0.009275,NaN,...,0.011968,-0.013507,-0.090535,-0.098404,-0.007680,-0.036071,-0.018259,0.047580,0.057851,1.000000
home_team_api_id,-0.155162,-0.155637,-0.155637,0.023674,-0.089011,1.000000,-0.017180,0.037712,-0.011265,NaN,...,-0.011029,-0.020139,-0.005223,0.004737,-0.021830,-0.017395,-0.047807,-0.049200,0.011665,-0.089011
away_team_api_id,-0.161508,-0.161867,-0.161867,0.022605,-0.098556,-0.017180,1.000000,-0.050139,0.005065,NaN,...,-0.099185,-0.083385,-0.038051,-0.041235,-0.021307,-0.097898,-0.089368,-0.048130,-0.016724,-0.098556
home_team_goal,0.045331,0.045875,0.045875,-0.020307,0.017903,0.037712,-0.050139,1.000000,-0.019159,NaN,...,0.014723,0.019104,0.026425,0.071208,0.063262,0.001112,0.009118,0.013547,0.038983,0.017903
away_team_goal,-0.011853,-0.010921,-0.010921,0.012219,-0.009275,-0.011265,0.005065,-0.019159,1.000000,NaN,...,-0.035773,-0.029818,0.002536,-0.018491,-0.039663,-0.013176,0.042985,-0.020874,-0.050455,-0.009275
home_player_X1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
home_player_X2,0.023522,0.021682,0.021682,-0.006812,0.374355,0.007510,0.010089,0.006489,-0.060065,NaN,...,-0.017976,-0.045486,-0.026043,-0.024158,-0.038005,-0.045975,-0.065893,0.020463,0.068683,0.374355
home_player_X3,0.005114,0.003774,0.003774,0.010121,0.198093,-0.032913,0.018415,0.023028,-0.031452,NaN,...,-0.024814,-0.017185,-0.015361,-0.000807,-0.005749,-0.033371,-0.021766,-0.022143,0.091223,0.198093
home_player_X4,0.036663,0.035412,0.035412,0.021433,0.378157,-0.010815,0.004171,0.032878,-0.024506,NaN,...,-0.036717,-0.026397,-0.041375,-0.033110,-0.066738,-0.037558,-0.071686,-0.009182,0.061437,0.378157
home_player_X5,-0.018757,-0.016949,-0.016949,-0.016651,-0.438204,0.003231,-0.017222,-0.005007,0.034973,NaN,...,0.022425,0.058160,0.043921,0.026321,0.066164,0.058117,0.078792,-0.010388,-0.068551,-0.438204
home_player_X6,0.124657,0.128753,0.128753,0.048808,-0.095177,-0.097875,-0.015820,-0.003552,0.018648,NaN,...,0.113478,0.095960,0.066921,0.111659,0.097314,0.094858,0.110002,0.119526,0.051708,-0.095177
home_player_X7,0.234991,0.235541,0.235541,0.027082,0.084820,-0.026921,-0.084263,0.054314,0.001704,NaN,...,0.019727,0.029382,0.010331,0.042242,0.035754,0.027678,0.022067,0.021705,0.049929,0.084820
home_player_X8,-0.177284,-0.181187,-0.181187,-0.033170,0.258613,0.023039,0.076784,-0.030131,-0.041709,NaN,...,-0.055165,-0.068389,-0.064463,-0.105151,-0.087044,-0.091604,-0.109966,-0.063361,-0.002325,0.258613
home_player_X9,-0.137775,-0.137584,-0.137584,0.013459,0.029334,0.066813,0.019398,-0.039215,0.008934,NaN,...,-0.049215,-0.077292,-0.019456,-0.034341,-0.064806,-0.028941,-0.030749,0.000484,-0.030836,0.029334
home_player_X10,0.162957,0.164366,0.164366,-0.003301,-0.188633,0.005265,-0.042370,0.034164,0.038540,NaN,...,0.042809,0.079736,0.041812,0.088607,0.100897,0.055706,0.065516,0.008074,0.009382,-0.188633
home_player_X11,-0.131051,-0.132430,-0.132430,-0.022021,0.139340,-0.044658,0.043361,0.000733,-0.055197,NaN,...,-0.013365,-0.051511,-0.033614,-0.065187,-0.091433,-0.042223,-0.046715,-0.013674,-0.017653,0.139340
away_player_X1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
away_player_X2,0.026790,0.025130,0.025130,0.021632,0.407427,0.012597,-0.026932,-0.006570,-0.003565,NaN,...,-0.118306,0.027678,-0.071126,0.018485,-0.031729,-0.026694,-0.029148,0.048637,0.084084,0.407427
away_player_X3,0.027520,0.026848,0.026848,0.009442,0.226360,-0.027722,-0.058896,-0.005776,0.001380,NaN,...,-0.092333,0.021092,-0.029436,0.027791,0.000822,0.001069,0.004217,0.047276,0.046056,0.226360
away_player_X4,0.030043,0.028574,0.028574,0.032161,0.365316,-0.012823,-0.029626,-0.015556,-0.000973,NaN,...,-0.115009,0.007621,-0.052350,0.016528,-0.031641,-0.014683,-0.016569,0.064227,0.066671,0.365316
away_player_X5,-0.016600,-0.014441,-0.014441,-0.032284,-0.444405,0.001128,0.013105,0.017193,0.019987,NaN,...,0.113376,-0.003303,0.085361,-0.011193,0.026096,0.036987,0.045867,-0.043545,-0.064235,-0.444405
away_player_X6,0.093434,0.097202,0.097202,-0.000992,-0.147103,-0.049555,-0.048956,-0.006887,-0.022914,NaN,...,0.142889,0.104835,0.120648,0.086875,0.108517,0.086304,0.101255,0.123223,0.039373,-0.147103
away_player_X7,0.276957,0.276382,0.276382,0.019090,0.100760,-0.065720,-0.022162,-0.015648,0.049273,NaN,...,0.003733,0.151956,-0.026078,0.075651,0.070294,0.084993,-0.001000,0.062872,0.008306,0.100760
away_player_X8,-0.186124,-0.189253,-0.189253,-0.007718,0.251316,0.044948,0.001462,0.008364,0.003482,NaN,...,-0.058229,-0.118902,-0.055557,-0.082336,-0.127429,-0.107302,-0.039343,-0.045946,0.052245,0.251316
away_player_X9,-0.151305,-0.150637,-0.150637,0.018407,0.068476,0.041090,0.074588,-0.013514,-0.048446,NaN,...,-0.095980,-0.076008,-0.077537,-0.013858,-0.030894,-0.031659,-0.088752,-0.079095,-0.062063,0.068476
away_player_X10,0.167553,0.167559,0.167559,-0.003016,-0.178758,-0.021679,-0.030286,-0.016313,-0.033721,NaN,...,0.022187,0.071357,0.034604,0.034546,0.094800,0.034958,0.048346,0.092119,-0.032321,-0.178758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
away_player_Y5,0.007189,0.004840,0.004840,0.030350,0.443889,0.009213,-0.012276,-0.011381,-0.013622,NaN,...,-0.116535,0.016831,-0.103261,0.003624,-0.028371,-0.030754,-0.042936,0.030004,0.064332,0.443889
away_player_Y6,-0.072505,-0.076206,-0.076206,0.022447,0.246724,0.047801,-0.006275,0.019453,0.030927,NaN,...,-0.161111,-0.085215,-0.126335,-0.074889,-0.108075,-0.053129,-0.050355,-0.096255,0.029392,0.246724
away_player_Y7,-0.225541,-0.227187,-0.227187,-0.021142,0.225188,0.065159,0.003098,0.022937,-0.039729,NaN,...,-0.104747,-0.180888,-0.051251,-0.126628,-0.085646,-0.115553,-0.028669,-0.102983,0.043356,0.225188
away_player_Y8,0.234080,0.237495,0.237495,0.016184,-0.219995,-0.044980,-0.035732,-0.005077,-0.001719,NaN,...,0.055500,0.154675,0.074817,0.094581,0.142302,0.132432,0.091548,0.091622,-0.003746,-0.219995
away_player_Y9,0.060781,0.061176,0.061176,-0.009955,0.018898,-0.022031,-0.084903,0.034470,0.063821,NaN,...,0.071214,0.038025,0.072896,-0.000452,-0.001326,0.041507,0.085436,0.034072,0.107571,0.018898
away_player_Y10,-0.157318,-0.157043,-0.157043,-0.003941,0.202948,0.018629,0.027208,0.030826,0.046527,NaN,...,-0.009439,-0.072477,-0.007030,-0.047652,-0.087976,-0.035509,-0.035285,-0.101549,0.053798,0.202948
away_player_Y11,0.114290,0.115164,0.115164,-0.022770,-0.132398,-0.028688,-0.004798,-0.033663,-0.052224,NaN,...,0.019951,0.078170,0.024224,0.033954,0.057036,0.022686,0.032966,0.129763,-0.043975,-0.132398
home_player_1,0.085120,0.087934,0.087934,-0.024727,0.113850,0.000073,0.005377,-0.001366,0.010713,NaN,...,0.016778,0.044738,0.026964,-0.032065,0.039183,-0.008114,0.037933,0.036061,0.017767,0.113850
home_player_2,0.052327,0.053133,0.053133,0.001452,-0.026941,-0.093606,0.043529,-0.038604,0.061195,NaN,...,0.015349,0.005994,0.017353,0.019417,0.040955,0.041230,0.056577,0.043366,-0.005400,-0.026941
home_player_3,0.177518,0.177339,0.177339,0.026313,0.008083,-0.058011,-0.029644,-0.018883,0.055694,NaN,...,0.021914,0.100234,0.052547,0.096618,0.050179,0.043983,0.083945,0.045790,0.016769,0.008083
home_player_4,0.157620,0.158273,0.158273,0.016176,-0.006270,-0.083840,-0.023009,-0.025755,0.054986,NaN,...,0.044364,0.024691,0.030120,0.081788,0.063979,0.021507,0.022205,0.090165,0.037905,-0.006270
home_player_5,0.029290,0.030317,0.030317,0.036872,-0.077283,-0.027049,-0.016191,-0.020534,0.029516,NaN,...,0.026537,0.080455,0.019433,0.011613,0.032151,0.047611,0.054344,0.052574,0.001501,-0.077283
home_player_6,0.127025,0.126404,0.126404,0.046676,-0.047279,-0.064685,0.000878,-0.018128,0.010097,NaN,...,0.071271,0.041007,0.006338,0.018426,0.052619,-0.009851,0.039071,0.042352,0.065272,-0.047279
home_player_7,0.184026,0.183981,0.183981,0.049702,-0.009425,-0.000813,-0.037573,0.000628,0.030664,NaN,...,0.062838,0.049387,0.026509,0.057742,0.073145,0.027003,0.082622,0.023661,0.065364,-0.009425
home_player_8,0.132279,0.134074,0.134074,0.043717,0.017328,-0.092235,-0.038315,-0.047419,0.028124,NaN,...,0.061691,0.056232,0.041477,0.025140,0.046173,0.092535,0.053925,0.082576,-0.005872,0.017328
home_player_9,0.035157,0.036619,0.036619,0.030119,-0.066906,-0.027052,0.006400,-0.034211,0.003857,NaN,...,0.046220,0.024332,0.036422,-0.014021,0.064586,0.032675,0.029846,0.031964,0.012409,-0.066906
home_player_10,0.140393,0.141615,0.141615,0.061862,0.076897,-0.052750,-0.025697,-0.028016,0.010610,NaN,...,0.079517,0.043320,0.031100,0.075512,0.056763,0.009863,0.066018,0.060952,0.073014,0.076897
home_player_11,0.047058,0.048058,0.048058,-0.007449,0.015899,-0.050440,-0.011936,-0.087533,0.027299,NaN,...,0.012090,0.066526,0.034651,0.063671,0.032098,0.025686,0.026001,0.059781,0.054736,0.015899
away_player_1,0.078131,0.081313,0.081313,-0.015058,0.115009,-0.032219,0.007361,0.029305,-0.023753,NaN,...,0.052083,0.041993,-0.039411,-0.053483,0.019511,0.053084,0.001806,0.064827,0.117899,0.115009
away_player_2,0.034097,0.035595,0.035595,-0.022663,-0.027631,0.000146,-0.051291,0.002552,-0.042135,NaN,...,0.130722,0.143092,0.037327,-0.025682,0.045129,0.073489,0.056285,0.093400,0.153888,-0.027631
away_player_3,0.142171,0.142568,0.142568,0.016421,0.011968,-0.011029,-0.099185,0.014723,-0.035773,NaN,...,1.000000,0.099548,0.140251,0.031728,0.086679,0.133989,0.057973,0.059469,0.039997,0.011968
away_player_4,0.173814,0.174333,0.174333,0.045897,-0.013507,-0.020139,-0.083385,0.019104,-0.029818,NaN,...,0.099548,1.000000,0.133411,0.104686,0.101022,0.106860,0.105795,0.122182,0.050762,-0.013507
away_player_5,0.017084,0.018041,0.018041,0.087980,-0.090535,-0.005223,-0.038051,0.026425,0.002536,NaN,...,0.140251,0.133411,1.000000,0.103781,0.094992,0.108682,0.112909,0.080948,0.004174,-0.090535
away_player_6,0.077242,0.076641,0.076641,0.068206,-0.098404,0.004737,-0.041235,0.071208,-0.018491,NaN,...,0.031728,0.104686,0.103781,1.000000,0.050423,0.075617,0.118734,0.132966,0.048598,-0.098404
away_player_7,0.188901,0.188922,0.188922,0.022223,-0.007680,-0.021830,-0.021307,0.063262,-0.039663,NaN,...,0.086679,0.101022,0.094992,0.050423,1.000000,0.035697,0.058355,0.070046,0.045604,-0.007680
away_player_8,0.075846,0.078047,0.078047,0.023593,-0.036071,-0.017395,-0.097898,0.001112,-0.013176,NaN,...,0.133989,0.106860,0.108682,0.075617,0.035697,1.000000,0.103430,0.030415,0.082823,-0.036071
away_player_9,0.117966,0.118706,0.118706,0.028204,-0.018259,-0.047807,-0.089368,0.009118,0.042985,NaN,...,0.057973,0.105795,0.112909,0.118734,0.058355,0.103430,1.000000,0.056117,0.056752,-0.018259
away_player_10,0.118446,0.120215,0.120215,0.083800,0.047580,-0.049200,-0.048130,0.013547,-0.020874,NaN,...,0.059469,0.122182,0.080948,0.132966,0.070046,0.030415,0.056117,1.000000,0.039427,0.047580
away_player_11,0.053210,0.054280,0.054280,0.023077,0.057851,0.011665,-0.016724,0.038983,-0.050455,NaN,...,0.039997,0.050762,0.004174,0.048598,0.045604,0.082823,0.056752,0.039427,1.000000,0.057851
match_api_id,0.572916,0.572730,0.572730,0.022703,1.000000,-0.089011,-0.098556,0.017903,-0.009275,NaN,...,0.011968,-0.013507,-0.090535,-0.098404,-0.007680,-0.036071,-0.018259,0.047580,0.057851,1.000000

In [524]:
targets = matches.apply(get_outcome, axis = 1)
match_stats = matches.apply(lambda x: get_match_features(x, matches, x = 20), axis = 1)
#features = pd.merge(, fifa_stats, on = 'match_api_id', how = 'left')
features = pd.merge(match_stats, targets, on = 'match_api_id', how = 'left')

features = pd.merge(features, targets, on = 'match_api_id', how = 'left')
matches = pd.concat([matches, targets], axis = 1)
features = matches.drop('outcome', axis = 1)


target = matches.loc[:,'outcome']
features = features.drop('home_team_goal', axis = 1)
features = features.drop('away_team_goal', axis = 1)
features = features.drop(["country_id", "league_id", "season", "stage", "match_api_id","date", 
        "away_team_api_id","goal","shoton","shotoff","foulcommit","card","cross","corner","possession"],axis = 1)

In [525]:
features.isnull().sum()

id                  0
home_team_api_id    0
home_player_X1      0
home_player_X2      0
home_player_X3      0
home_player_X4      0
home_player_X5      0
home_player_X6      0
home_player_X7      0
home_player_X8      0
home_player_X9      0
home_player_X10     0
home_player_X11     0
away_player_X1      0
away_player_X2      0
away_player_X3      0
away_player_X4      0
away_player_X5      0
away_player_X6      0
away_player_X7      0
away_player_X8      0
away_player_X9      0
away_player_X10     0
away_player_X11     0
home_player_Y1      0
home_player_Y2      0
home_player_Y3      0
home_player_Y4      0
home_player_Y5      0
home_player_Y6      0
                   ..
away_player_Y4      0
away_player_Y5      0
away_player_Y6      0
away_player_Y7      0
away_player_Y8      0
away_player_Y9      0
away_player_Y10     0
away_player_Y11     0
home_player_1       0
home_player_2       0
home_player_3       0
home_player_4       0
home_player_5       0
home_player_6       0
home_player_7       0
home_player_8       0
home_player_9       0
home_player_10      0
home_player_11      0
away_player_1       0
away_player_2       0
away_player_3       0
away_player_4       0
away_player_5       0
away_player_6       0
away_player_7       0
away_player_8       0
away_player_9       0
away_player_10      0
away_player_11      0
Length: 68, dtype: int64

In [526]:
team_attributes = pd.read_sql("""SELECT * FROM Team_Attributes;""", conn)

In [527]:
print(team_attributes.columns.values)

['id' 'team_fifa_api_id' 'team_api_id' 'date' 'buildUpPlaySpeed'
 'buildUpPlaySpeedClass' 'buildUpPlayDribbling'
 'buildUpPlayDribblingClass' 'buildUpPlayPassing'
 'buildUpPlayPassingClass' 'buildUpPlayPositioningClass'
 'chanceCreationPassing' 'chanceCreationPassingClass'
 'chanceCreationCrossing' 'chanceCreationCrossingClass'
 'chanceCreationShooting' 'chanceCreationShootingClass'
 'chanceCreationPositioningClass' 'defencePressure' 'defencePressureClass'
 'defenceAggression' 'defenceAggressionClass' 'defenceTeamWidth'
 'defenceTeamWidthClass' 'defenceDefenderLineClass']

In [528]:
print(team_attributes.isnull().sum())

id                                  0
team_fifa_api_id                    0
team_api_id                         0
date                                0
buildUpPlaySpeed                    0
buildUpPlaySpeedClass               0
buildUpPlayDribbling              969
buildUpPlayDribblingClass           0
buildUpPlayPassing                  0
buildUpPlayPassingClass             0
buildUpPlayPositioningClass         0
chanceCreationPassing               0
chanceCreationPassingClass          0
chanceCreationCrossing              0
chanceCreationCrossingClass         0
chanceCreationShooting              0
chanceCreationShootingClass         0
chanceCreationPositioningClass      0
defencePressure                     0
defencePressureClass                0
defenceAggression                   0
defenceAggressionClass              0
defenceTeamWidth                    0
defenceTeamWidthClass               0
defenceDefenderLineClass            0
dtype: int64

In [529]:
team_attributes.dropna(axis = 1)

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,buildUpPlayPositioningClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,Little,50,Mixed,Organised,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,Normal,56,Mixed,Organised,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,Normal,54,Mixed,Organised,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,4,77,8485,2010-02-22 00:00:00,70,Fast,Little,70,Long,Organised,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,Little,52,Mixed,Organised,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover
5,6,77,8485,2012-02-22 00:00:00,58,Balanced,Little,62,Mixed,Organised,...,55,Normal,Organised,40,Medium,40,Press,60,Normal,Cover
6,7,77,8485,2013-09-20 00:00:00,62,Balanced,Little,45,Mixed,Organised,...,55,Normal,Organised,42,Medium,42,Press,60,Normal,Cover
7,8,77,8485,2014-09-19 00:00:00,58,Balanced,Normal,62,Mixed,Organised,...,57,Normal,Organised,41,Medium,42,Press,60,Normal,Cover
8,9,77,8485,2015-09-10 00:00:00,59,Balanced,Normal,53,Mixed,Organised,...,63,Normal,Free Form,49,Medium,45,Press,63,Normal,Cover
9,10,614,8576,2010-02-22 00:00:00,60,Balanced,Little,40,Mixed,Organised,...,55,Normal,Organised,30,Deep,70,Double,30,Narrow,Offside Trap
10,11,614,8576,2011-02-22 00:00:00,65,Balanced,Little,45,Mixed,Organised,...,50,Normal,Organised,45,Medium,45,Press,50,Normal,Cover
11,12,614,8576,2012-02-22 00:00:00,59,Balanced,Little,52,Mixed,Organised,...,52,Normal,Organised,38,Medium,47,Press,53,Normal,Cover
12,13,614,8576,2013-09-20 00:00:00,59,Balanced,Little,52,Mixed,Organised,...,52,Normal,Organised,38,Medium,47,Press,53,Normal,Cover
13,14,614,8576,2014-09-19 00:00:00,59,Balanced,Normal,52,Mixed,Organised,...,52,Normal,Organised,38,Medium,47,Press,53,Normal,Cover
14,15,614,8576,2015-09-10 00:00:00,59,Balanced,Normal,52,Mixed,Organised,...,52,Normal,Organised,38,Medium,47,Press,53,Normal,Cover
15,16,47,8564,2010-02-22 00:00:00,45,Balanced,Little,30,Short,Free Form,...,70,Lots,Free Form,30,Deep,35,Press,60,Normal,Offside Trap
16,17,47,8564,2011-02-22 00:00:00,65,Balanced,Little,50,Mixed,Organised,...,50,Normal,Free Form,50,Medium,50,Press,50,Normal,Offside Trap
17,18,47,8564,2012-02-22 00:00:00,45,Balanced,Little,50,Mixed,Organised,...,50,Normal,Free Form,45,Medium,45,Press,50,Normal,Cover
18,19,47,8564,2013-09-20 00:00:00,48,Balanced,Little,54,Mixed,Organised,...,64,Normal,Free Form,48,Medium,49,Press,53,Normal,Cover
19,20,47,8564,2014-09-19 00:00:00,48,Balanced,Lots,52,Mixed,Organised,...,75,Lots,Organised,58,Medium,57,Press,49,Normal,Cover
20,21,47,8564,2015-09-10 00:00:00,48,Balanced,Lots,52,Mixed,Organised,...,69,Lots,Organised,58,Medium,57,Press,49,Normal,Cover
21,22,1901,10215,2010-02-22 00:00:00,30,Slow,Little,30,Short,Organised,...,55,Normal,Organised,30,Deep,30,Contain,30,Narrow,Offside Trap
22,23,1901,10215,2011-02-22 00:00:00,30,Slow,Little,50,Mixed,Organised,...,55,Normal,Organised,30,Deep,45,Press,65,Normal,Cover
23,24,1901,10215,2012-02-22 00:00:00,45,Balanced,Little,44,Mixed,Organised,...,60,Normal,Organised,52,Medium,38,Press,61,Normal,Cover
24,25,1901,10215,2013-09-20 00:00:00,45,Balanced,Little,44,Mixed,Organised,...,60,Normal,Organised,52,Medium,38,Press,61,Normal,Cover
25,26,1901,10215,2014-09-19 00:00:00,52,Balanced,Normal,44,Mixed,Organised,...,60,Normal,Organised,39,Medium,38,Press,61,Normal,Cover
26,27,1901,10215,2015-09-10 00:00:00,53,Balanced,Normal,44,Mixed,Organised,...,60,Normal,Organised,39,Medium,38,Press,61,Normal,Cover
27,28,650,10217,2010-02-22 00:00:00,30,Slow,Little,35,Mixed,Organised,...,65,Normal,Organised,30,Deep,30,Contain,30,Narrow,Cover
28,29,650,10217,2011-02-22 00:00:00,53,Balanced,Little,53,Mixed,Organised,...,66,Normal,Organised,46,Medium,62,Press,65,Normal,Cover
29,30,650,10217,2012-02-22 00:00:00,38,Balanced,Little,44,Mixed,Organised,...,44,Normal,Organised,50,Medium,58,Press,62,Normal,Cover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1428,1429,435,7955,2012-02-22 00:00:00,49,Balanced,Little,50,Mixed,Organised,...,34,Normal,Organised,34,Medium,31,Contain,51,Normal,Cover
1429,1430,1742,9868,2010-02-22 00:00:00,30,Slow,Little,30,Short,Organised,...,70,Lots,Organised,45,Medium,50,Press,45,Normal,Cover
1430,1431,1742,9868,2011-02-22 00:00:00,40,Balanced,Little,58,Mixed,Organised,...,49,Normal,Organised,46,Medium,52,Press,67,Wide,Cover
1431,1432,1742,9868,2012-02-22 00:00:00,60,Balanced,Little,44,Mixed,Organised,...,41,Normal,Organised,49,Medium,54,Press,50,Normal,Cover
1432,1433,1742,9868,2013-09-20 00:00:00,60,Balanced,Little,44,Mixed,Organised,...,41,Normal,Organised,49,Medium,54,Press,50,Normal,Cover
1433,1434,900,10192,2010-02-22 00:00:00,55,Balanced,Little,55,Mixed,Organised,...,60,Normal,Organised,55,Medium,55,Press,60,Normal,Offside Trap
1434,1435,900,10192,2011-02-22 00:00:00,60,Balanced,Little,57,Mixed,Organised,...,68,Lots,Organised,48,Medium,49,Press,61,Normal,Cover
1435,1436,900,10192,2012-02-22 00:00:00,52,Balanced,Little,69,Long,Organised,...,46,Normal,Organised,44,Medium,34,Press,50,Normal,Cover
1436,1437,900,10192,2013-09-20 00:00:00,52,Balanced,Little,69,Long,Organised,...,46,Normal,Organised,44,Medium,34,Press,50,Normal,Cover
1437,1438,900,10192,2014-09-19 00:00:00,52,Balanced,Normal,64,Mixed,Organised,...,46,Normal,Organised,44,Medium,34,Press,50,Normal,Cover
1438,1439,900,10192,2015-09-10 00:00:00,52,Balanced,Normal,64,Mixed,Organised,...,46,Normal,Organised,44,Medium,34,Press,50,Normal,Cover
1439,1440,110749,8021,2010-02-22 00:00:00,55,Balanced,Little,60,Mixed,Organised,...,70,Lots,Organised,70,High,70,Double,70,Wide,Cover
1440,1441,110749,8021,2011-02-22 00:00:00,54,Balanced,Little,37,Mixed,Organised,...,37,Normal,Organised,47,Medium,58,Press,52,Normal,Cover
1441,1442,110749,8021,2012-02-22 00:00:00,33,Slow,Little,38,Mixed,Organised,...,73,Lots,Organised,58,Medium,47,Press,52,Normal,Cover
1442,1443,110749,8021,2013-09-20 00:00:00,33,Slow,Little,38,Mixed,Organised,...,48,Normal,Organised,58,Medium,47,Press,52,Normal,Cover
1443,1444,110749,8021,2014-09-19 00:00:00,33,Slow,Normal,51,Mixed,Organised,...,48,Normal,Organised,58,Medium,38,Press,52,Normal,Cover
1444,1445,244,8394,2010-02-22 00:00:00,30,Slow,Little,30,Short,Free Form,...,70,Lots,Organised,40,Medium,30,Contain,45,Normal,Offside Trap
1445,1446,244,8394,2011-02-22 00:00:00,43,Balanced,Little,40,Mixed,Organised,...,42,Normal,Organised,38,Medium,40,Press,53,Normal,Cover
1446,1447,244,8394,2012-02-22 00:00:00,34,Balanced,Little,23,Short,Organised,...,57,Normal,Organised,51,Medium,46,Press,61,Normal,Cover
1447,1448,244,8394,2013-09-20 00:00:00,38,Balanced,Little,23,Short,Organised,...,57,Normal,Organised,51,Medium,46,Press,61,Normal,Cover
1448,1449,244,8394,2014-09-19 00:00:00,38,Balanced,Normal,35,Mixed,Organised,...,57,Normal,Organised,51,Medium,46,Press,61,Normal,Cover
1449,1450,244,8394,2015-09-10 00:00:00,52,Balanced,Normal,50,Mixed,Organised,...,57,Normal,Organised,48,Medium,43,Press,49,Normal,Cover
1450,1451,112512,8027,2014-09-19 00:00:00,54,Balanced,Normal,40,Mixed,Organised,...,52,Normal,Organised,44,Medium,47,Press,52,Normal,Cover
1451,1452,112512,8027,2015-09-10 00:00:00,54,Balanced,Normal,40,Mixed,Organised,...,52,Normal,Organised,44,Medium,47,Press,52,Normal,Cover
1452,1453,15005,10000,2010-02-22 00:00:00,65,Balanced,Little,60,Mixed,Organised,...,50,Normal,Organised,70,High,60,Press,70,Wide,Cover
1453,1454,15005,10000,2011-02-22 00:00:00,52,Balanced,Little,52,Mixed,Organised,...,53,Normal,Organised,46,Medium,48,Press,53,Normal,Cover
1454,1455,15005,10000,2012-02-22 00:00:00,54,Balanced,Little,51,Mixed,Organised,...,50,Normal,Organised,44,Medium,55,Press,53,Normal,Cover
1455,1456,15005,10000,2013-09-20 00:00:00,54,Balanced,Little,51,Mixed,Organised,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1456,1457,15005,10000,2014-09-19 00:00:00,54,Balanced,Normal,51,Mixed,Organised,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1457,1458,15005,10000,2015-09-10 00:00:00,54,Balanced,Normal,51,Mixed,Organised,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover

In [530]:
numeric_cols=team_attributes.select_dtypes(numerics)
print(numeric_cols.columns.values)

['id' 'team_fifa_api_id' 'team_api_id' 'buildUpPlaySpeed'
 'buildUpPlayDribbling' 'buildUpPlayPassing' 'chanceCreationPassing'
 'chanceCreationCrossing' 'chanceCreationShooting' 'defencePressure'
 'defenceAggression' 'defenceTeamWidth']

In [531]:
team_att_features = team_attributes.drop(["id","buildUpPlaySpeed","buildUpPlayDribbling"
                                          ,"buildUpPlayPassing","chanceCreationPassing","chanceCreationCrossing",
                                          "chanceCreationShooting","defencePressure","defenceAggression","defenceTeamWidth"],axis=1)

In [532]:
team_att_features.columns.values

array(['team_fifa_api_id', 'team_api_id', 'date', 'buildUpPlaySpeedClass',
       'buildUpPlayDribblingClass', 'buildUpPlayPassingClass',
       'buildUpPlayPositioningClass', 'chanceCreationPassingClass',
       'chanceCreationCrossingClass', 'chanceCreationShootingClass',
       'chanceCreationPositioningClass', 'defencePressureClass',
       'defenceAggressionClass', 'defenceTeamWidthClass',
       'defenceDefenderLineClass'], dtype=object)

In [533]:
team_att_features['buildUpPlaySpeedClass'].unique()

array(['Balanced', 'Fast', 'Slow'], dtype=object)

In [534]:
team_att_features.buildUpPlaySpeedClass.replace(to_replace=dict(Slow=1, Balanced=2, Fast=3), inplace=True)

In [535]:
team_att_features['buildUpPlayDribblingClass'].unique()

array(['Little', 'Normal', 'Lots'], dtype=object)

In [536]:
team_att_features.buildUpPlayDribblingClass.replace(to_replace=dict(Little=1, Normal=2, Lots=3), inplace=True)

In [537]:
team_att_features['buildUpPlayPassingClass'].unique()

array(['Mixed', 'Long', 'Short'], dtype=object)

In [538]:
team_att_features.buildUpPlayPassingClass.replace(to_replace=dict(Short=1, Mixed=2, Long=3), inplace=True)

In [539]:
team_att_features['buildUpPlayPositioningClass'].unique()

array(['Organised', 'Free Form'], dtype=object)

In [540]:
team_att_features['chanceCreationPassingClass'].unique()

array(['Normal', 'Risky', 'Safe'], dtype=object)

In [541]:
team_att_features.chanceCreationPassingClass.replace(to_replace=dict(Safe=1, Normal=2, Risky=3), inplace=True)

In [542]:
team_att_features['chanceCreationCrossingClass'].unique()

array(['Normal', 'Lots', 'Little'], dtype=object)

In [543]:
team_att_features.chanceCreationCrossingClass.replace(to_replace=dict(Little=1, Normal=2, Lots=3), inplace=True)

In [544]:
team_att_features['chanceCreationShootingClass'].unique()

array(['Normal', 'Lots', 'Little'], dtype=object)

In [545]:
team_att_features.chanceCreationShootingClass.replace(to_replace=dict(Little=1, Normal=2, Lots=3), inplace=True)

In [546]:
team_att_features['chanceCreationPositioningClass'].unique()

array(['Organised', 'Free Form'], dtype=object)

In [547]:
team_att_features['defencePressureClass'].unique()

array(['Medium', 'Deep', 'High'], dtype=object)

In [548]:
team_att_features.defencePressureClass.replace(to_replace=dict(Medium=1, High=2,Deep = 3), inplace=True)

In [549]:
team_att_features['defenceAggressionClass'].unique()

array(['Press', 'Double', 'Contain'], dtype=object)

In [550]:
team_att_features['defenceTeamWidthClass'].unique()

array(['Normal', 'Wide', 'Narrow'], dtype=object)

In [551]:
team_att_features.defenceTeamWidthClass.replace(to_replace=dict(Narrow=1, Normal=2,Wide=3), inplace=True)

In [552]:
team_att_features['defenceDefenderLineClass'].unique()

array(['Cover', 'Offside Trap'], dtype=object)

In [553]:
team_att_features.head(len(team_att_features.values))

,team_fifa_api_id,team_api_id,date,buildUpPlaySpeedClass,buildUpPlayDribblingClass,buildUpPlayPassingClass,buildUpPlayPositioningClass,chanceCreationPassingClass,chanceCreationCrossingClass,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressureClass,defenceAggressionClass,defenceTeamWidthClass,defenceDefenderLineClass
0,434,9930,2010-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
1,434,9930,2014-09-19 00:00:00,2,2,2,Organised,2,2,2,Organised,1,Press,2,Cover
2,434,9930,2015-09-10 00:00:00,2,2,2,Organised,2,2,2,Organised,1,Press,2,Cover
3,77,8485,2010-02-22 00:00:00,3,1,3,Organised,3,3,3,Organised,1,Double,3,Cover
4,77,8485,2011-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
5,77,8485,2012-02-22 00:00:00,2,1,2,Organised,2,3,2,Organised,1,Press,2,Cover
6,77,8485,2013-09-20 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
7,77,8485,2014-09-19 00:00:00,2,2,2,Organised,2,3,2,Organised,1,Press,2,Cover
8,77,8485,2015-09-10 00:00:00,2,2,2,Organised,2,3,2,Free Form,1,Press,2,Cover
9,614,8576,2010-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,3,Double,1,Offside Trap
10,614,8576,2011-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
11,614,8576,2012-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
12,614,8576,2013-09-20 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
13,614,8576,2014-09-19 00:00:00,2,2,2,Organised,2,2,2,Organised,1,Press,2,Cover
14,614,8576,2015-09-10 00:00:00,2,2,2,Organised,2,2,2,Organised,1,Press,2,Cover
15,47,8564,2010-02-22 00:00:00,2,1,1,Free Form,2,2,3,Free Form,3,Press,2,Offside Trap
16,47,8564,2011-02-22 00:00:00,2,1,2,Organised,2,2,2,Free Form,1,Press,2,Offside Trap
17,47,8564,2012-02-22 00:00:00,2,1,2,Organised,2,1,2,Free Form,1,Press,2,Cover
18,47,8564,2013-09-20 00:00:00,2,1,2,Organised,2,2,2,Free Form,1,Press,2,Cover
19,47,8564,2014-09-19 00:00:00,2,3,2,Organised,2,2,3,Organised,1,Press,2,Cover
20,47,8564,2015-09-10 00:00:00,2,3,2,Organised,2,2,3,Organised,1,Press,2,Cover
21,1901,10215,2010-02-22 00:00:00,1,1,1,Organised,2,2,2,Organised,3,Contain,1,Offside Trap
22,1901,10215,2011-02-22 00:00:00,1,1,2,Organised,2,2,2,Organised,3,Press,2,Cover
23,1901,10215,2012-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
24,1901,10215,2013-09-20 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
25,1901,10215,2014-09-19 00:00:00,2,2,2,Organised,2,2,2,Organised,1,Press,2,Cover
26,1901,10215,2015-09-10 00:00:00,2,2,2,Organised,2,2,2,Organised,1,Press,2,Cover
27,650,10217,2010-02-22 00:00:00,1,1,2,Organised,1,2,2,Organised,3,Contain,1,Cover
28,650,10217,2011-02-22 00:00:00,2,1,2,Organised,2,3,2,Organised,1,Press,2,Cover
29,650,10217,2012-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1428,435,7955,2012-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Contain,2,Cover
1429,1742,9868,2010-02-22 00:00:00,1,1,1,Organised,2,2,3,Organised,1,Press,2,Cover
1430,1742,9868,2011-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,3,Cover
1431,1742,9868,2012-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
1432,1742,9868,2013-09-20 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
1433,900,10192,2010-02-22 00:00:00,2,1,2,Organised,2,3,2,Organised,1,Press,2,Offside Trap
1434,900,10192,2011-02-22 00:00:00,2,1,2,Organised,2,3,3,Organised,1,Press,2,Cover
1435,900,10192,2012-02-22 00:00:00,2,1,3,Organised,2,3,2,Organised,1,Press,2,Cover
1436,900,10192,2013-09-20 00:00:00,2,1,3,Organised,2,3,2,Organised,1,Press,2,Cover
1437,900,10192,2014-09-19 00:00:00,2,2,2,Organised,2,2,2,Organised,1,Press,2,Cover
1438,900,10192,2015-09-10 00:00:00,2,2,2,Organised,2,2,2,Organised,1,Press,2,Cover
1439,110749,8021,2010-02-22 00:00:00,2,1,2,Organised,1,2,3,Organised,2,Double,3,Cover
1440,110749,8021,2011-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
1441,110749,8021,2012-02-22 00:00:00,1,1,2,Organised,3,2,3,Organised,1,Press,2,Cover
1442,110749,8021,2013-09-20 00:00:00,1,1,2,Organised,3,2,2,Organised,1,Press,2,Cover
1443,110749,8021,2014-09-19 00:00:00,1,2,2,Organised,2,2,2,Organised,1,Press,2,Cover
1444,244,8394,2010-02-22 00:00:00,1,1,1,Free Form,2,2,3,Organised,1,Contain,2,Offside Trap
1445,244,8394,2011-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
1446,244,8394,2012-02-22 00:00:00,2,1,1,Organised,2,2,2,Organised,1,Press,2,Cover
1447,244,8394,2013-09-20 00:00:00,2,1,1,Organised,2,2,2,Organised,1,Press,2,Cover
1448,244,8394,2014-09-19 00:00:00,2,2,2,Organised,2,2,2,Organised,1,Press,2,Cover
1449,244,8394,2015-09-10 00:00:00,2,2,2,Organised,2,2,2,Organised,1,Press,2,Cover
1450,112512,8027,2014-09-19 00:00:00,2,2,2,Organised,3,2,2,Organised,1,Press,2,Cover
1451,112512,8027,2015-09-10 00:00:00,2,2,2,Organised,2,2,2,Organised,1,Press,2,Cover
1452,15005,10000,2010-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,2,Press,3,Cover
1453,15005,10000,2011-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
1454,15005,10000,2012-02-22 00:00:00,2,1,2,Organised,2,2,2,Organised,1,Press,2,Cover
1455,15005,10000,2013-09-20 00:00:00,2,1,2,Organised,2,2,1,Organised,1,Press,2,Cover
1456,15005,10000,2014-09-19 00:00:00,2,2,2,Organised,2,2,1,Organised,1,Press,2,Cover
1457,15005,10000,2015-09-10 00:00:00,2,2,2,Organised,2,2,1,Organised,1,Press,2,Cover

In [554]:
team_att_features = pd.get_dummies(team_att_features,columns = ['defenceDefenderLineClass','defenceAggressionClass',
                    'chanceCreationPositioningClass','buildUpPlayPositioningClass'])

In [555]:
len(team_att_features['team_api_id'].unique())

288

In [556]:
team_att_features.sort_values(by = 'date',ascending = False)
team_att_features = team_att_features.drop_duplicates(subset='team_api_id', keep="first")
team_att_features.head(len(team_att_features))

,team_fifa_api_id,team_api_id,date,buildUpPlaySpeedClass,buildUpPlayDribblingClass,buildUpPlayPassingClass,chanceCreationPassingClass,chanceCreationCrossingClass,chanceCreationShootingClass,defencePressureClass,defenceTeamWidthClass,defenceDefenderLineClass_Cover,defenceDefenderLineClass_Offside Trap,defenceAggressionClass_Contain,defenceAggressionClass_Double,defenceAggressionClass_Press,chanceCreationPositioningClass_Free Form,chanceCreationPositioningClass_Organised,buildUpPlayPositioningClass_Free Form,buildUpPlayPositioningClass_Organised
0,434,9930,2010-02-22 00:00:00,2,1,2,2,2,2,1,2,1,0,0,0,1,0,1,0,1
3,77,8485,2010-02-22 00:00:00,3,1,3,3,3,3,1,3,1,0,0,1,0,0,1,0,1
9,614,8576,2010-02-22 00:00:00,2,1,2,2,2,2,3,1,0,1,0,1,0,0,1,0,1
15,47,8564,2010-02-22 00:00:00,2,1,1,2,2,3,3,2,0,1,0,0,1,1,0,1,0
21,1901,10215,2010-02-22 00:00:00,1,1,1,2,2,2,3,1,0,1,1,0,0,0,1,0,1
27,650,10217,2010-02-22 00:00:00,1,1,2,1,2,2,3,1,1,0,1,0,0,0,1,0,1
33,245,8593,2010-02-22 00:00:00,1,1,1,2,2,3,3,1,1,0,1,0,0,0,1,1,0
39,1861,9865,2010-02-22 00:00:00,2,1,2,2,2,3,2,1,1,0,0,0,1,0,1,0,1
45,229,8635,2010-02-22 00:00:00,2,1,2,3,2,2,2,3,1,0,0,0,1,0,1,0,1
51,1530,8121,2010-02-22 00:00:00,2,1,2,2,2,2,3,1,0,1,0,0,1,0,1,0,1
57,111082,8322,2010-02-22 00:00:00,1,1,2,2,2,3,1,3,1,0,0,1,0,0,1,0,1
59,111989,108893,2010-02-22 00:00:00,2,1,2,1,2,1,3,2,1,0,0,0,1,0,1,0,1
65,159,9912,2010-02-22 00:00:00,2,1,2,2,3,2,1,2,1,0,0,0,1,0,1,0,1
68,112513,158085,2014-09-19 00:00:00,3,2,2,2,2,2,1,2,1,0,0,0,1,0,1,0,1
70,1,9825,2010-02-22 00:00:00,2,1,1,1,2,2,3,2,1,0,0,0,1,1,0,1,0
76,2,10252,2010-02-22 00:00:00,3,1,2,2,3,2,3,1,1,0,0,1,0,1,0,0,1
82,39,8524,2010-02-22 00:00:00,2,1,2,2,1,2,3,2,0,1,1,0,0,0,1,0,1
88,448,8315,2010-02-22 00:00:00,2,1,2,2,3,2,3,2,1,0,0,1,0,0,1,0,1
94,240,9906,2010-02-22 00:00:00,2,1,1,2,2,3,2,2,0,1,0,0,1,1,0,1,0
100,100409,8406,2010-02-22 00:00:00,2,1,2,2,3,3,1,2,1,0,0,0,1,0,1,0,1
106,57,8583,2010-02-22 00:00:00,1,1,3,2,2,2,3,1,1,0,0,0,1,0,1,0,1
112,1906,10229,2010-02-22 00:00:00,2,1,2,2,1,2,3,2,1,0,1,0,0,0,1,0,1
118,241,8634,2010-02-22 00:00:00,2,1,1,2,2,3,2,3,0,1,1,0,0,1,0,1,0
124,1848,9976,2010-02-22 00:00:00,1,1,1,1,2,2,1,2,0,1,1,0,0,0,1,1,0
130,896,9931,2010-02-22 00:00:00,2,1,2,2,2,2,1,2,1,0,0,0,1,0,1,0,1
136,32,8178,2010-02-22 00:00:00,3,1,1,3,3,3,2,3,1,0,0,0,1,0,1,0,1
142,21,9823,2010-02-22 00:00:00,2,1,2,2,3,3,2,2,1,0,0,0,1,1,0,1,0
148,675,9993,2010-02-22 00:00:00,2,1,2,2,2,2,2,3,1,0,0,1,0,0,1,0,1
152,1897,10211,2011-02-22 00:00:00,2,1,2,2,2,2,1,2,1,0,0,0,1,0,1,1,0
155,1889,9807,2010-02-22 00:00:00,1,1,1,2,2,2,3,1,0,1,1,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1895,9771,2010-02-22 00:00:00,2,1,2,2,2,2,1,2,1,0,0,0,1,0,1,0,1
1307,461,10267,2010-02-22 00:00:00,1,1,1,2,2,3,1,2,0,1,0,0,1,0,1,1,0
1313,110456,9873,2010-02-22 00:00:00,2,1,3,2,2,2,3,1,1,0,0,0,1,0,1,0,1
1319,462,10281,2010-02-22 00:00:00,2,1,2,2,1,2,3,1,1,0,0,0,1,0,1,0,1
1325,206,9876,2012-02-22 00:00:00,2,1,2,2,2,2,1,2,1,0,0,0,1,0,1,0,1
1329,36,10269,2010-02-22 00:00:00,3,1,1,2,3,3,1,2,1,0,0,0,1,0,1,0,1
1335,483,10205,2010-02-22 00:00:00,2,1,1,2,2,3,1,3,0,1,1,0,0,1,0,1,0
1341,1909,8277,2010-02-22 00:00:00,2,1,2,2,2,2,3,1,1,0,1,0,0,0,1,0,1
1347,1887,7844,2010-02-22 00:00:00,1,1,1,2,2,2,3,1,0,1,1,0,0,0,1,0,1
1353,665,10238,2010-02-22 00:00:00,1,1,1,2,2,2,3,1,1,0,1,0,0,0,1,0,1
1359,100651,9839,2010-02-22 00:00:00,2,1,2,2,2,2,1,2,1,0,0,0,1,0,1,0,1
1363,110913,8475,2013-09-20 00:00:00,2,1,2,2,1,2,3,2,1,0,0,0,1,1,0,0,1
1366,1795,9817,2010-02-22 00:00:00,3,1,3,3,3,2,2,2,1,0,0,1,0,0,1,0,1
1372,38,8697,2010-02-22 00:00:00,3,1,2,3,2,3,2,3,1,0,0,0,1,0,1,0,1
1378,109,8659,2010-02-22 00:00:00,2,1,2,3,3,2,2,3,1,0,0,1,0,0,1,0,1
1384,19,8654,2010-02-22 00:00:00,2,1,1,1,3,2,3,1,1,0,0,1,0,0,1,0,1
1390,681,10001,2010-02-22 00:00:00,2,1,2,2,2,2,2,3,1,0,0,1,0,0,1,0,1
1394,301,8024,2011-02-22 00:00:00,2,1,2,2,3,2,1,2,1,0,0,0,1,0,1,0,1
1398,1917,8528,2010-02-22 00:00:00,3,1,3,3,3,2,1,2,1,0,0,1,0,0,1,0,1
1404,1907,8525,2010-02-22 00:00:00,2,1,1,1,2,2,3,1,1,0,1,0,0,0,1,0,1
1408,1873,10265,2010-02-22 00:00:00,2,1,2,2,2,3,2,2,1,0,0,1,0,0,1,0,1
1414,175,8721,2010-02-22 00:00:00,2,1,2,2,2,3,1,2,1,0,0,0,1,0,1,0,1
1420,110,8602,2010-02-22 00:00:00,3,1,3,3,3,3,2,3,1,0,0,1,0,0,1,0,1
1426,435,7955,2010-02-22 00:00:00,2,1,2,2,3,2,1,2,1,0,0,0,1,0,1,0,1
1429,1742,9868,2010-02-22 00:00:00,1,1,1,2,2,3,1,2,1,0,0,0,1,0,1,0,1
1433,900,10192,2010-02-22 00:00:00,2,1,2,2,3,2,1,2,0,1,0,0,1,0,1,0,1
1439,110749,8021,2010-02-22 00:00:00,2,1,2,1,2,3,2,3,1,0,0,1,0,0,1,0,1
1444,244,8394,2010-02-22 00:00:00,1,1,1,2,2,3,1,2,0,1,1,0,0,0,1,1,0
1450,112512,8027,2014-09-19 00:00:00,2,2,2,3,2,2,1,2,1,0,0,0,1,0,1,0,1
1452,15005,10000,2010-02-22 00:00:00,2,1,2,2,2,2,2,3,1,0,0,0,1,0,1,0,1

In [557]:
team_att_features = team_att_features.drop("date",axis=1)

In [558]:
matches['home_team_api_id'].unique()

array([ 9825,  8668,  9879,  8456, 10261, 10172,  9798,  8659,  8654,
        8528,  8650, 10260,  9850,  8472, 10003,  8586, 10252,  8455,
        8466, 10194, 10249,  4087,  8481,  9831,  9847,  9837,  9851,
        9853,  9874, 10242,  7794,  8639,  8689,  9941,  8592,  8576,
        8521,  9748,  9873,  9827,  9789,  9904,  8358,  8406,  9790,
        9810,  8357,  9788,  8178,  8697,  8165,  8226,  9823, 10189,
       10269,  8721,  9905,  8194,  8524,  8535, 10233,  9885,  8564,
        8540,  9878,  8686,  8551,  8529,  8533,  8636,  8543, 10167,
        8600,  9857,  8530,  9875,  9882,  9804,  8315,  8633,  8634,
        8302,  8581,  8394,  9910,  8661,  8370,  9783,  9864,  8560,
        8371, 10267,  8305,  7878,  8558, 10281,  9906,  8603],
      dtype=int64)

In [559]:
matches['away_team_api_id'].unique()

array([ 8472, 10260,  9850,  8466,  8586, 10003, 10194,  8650, 10252,
        8455,  8668, 10261,  9825,  9798,  8528,  8456,  9879,  8654,
       10172,  8659,  9941,  9827,  8521,  8576,  8689,  8592,  9748,
        8639,  7794,  9873,  9831,  9847, 10242,  9851,  4087,  8481,
        9853,  9837, 10249,  9874,  8697, 10189,  9905,  8194,  8165,
        8178,  9823,  8226, 10269,  8358,  8406,  8721,  8357,  9810,
        9904,  9790,  9789,  9788,  8543,  8600,  8529, 10167,  9882,
        9875,  8636,  8530,  9804,  8551,  9878,  8535,  9857,  8564,
        8686,  8533,  8540,  8524, 10233,  9885,  8603, 10267,  8560,
        8305,  9906, 10281,  9864,  8558,  7878,  8371,  8370,  8315,
        8581,  8394,  8661,  9910,  8302,  8633,  9783,  8634],
      dtype=int64)

In [560]:
print(features.columns.values)
print(team_att_features.columns.values)

['id' 'home_team_api_id' 'home_player_X1' 'home_player_X2'
 'home_player_X3' 'home_player_X4' 'home_player_X5' 'home_player_X6'
 'home_player_X7' 'home_player_X8' 'home_player_X9' 'home_player_X10'
 'home_player_X11' 'away_player_X1' 'away_player_X2' 'away_player_X3'
 'away_player_X4' 'away_player_X5' 'away_player_X6' 'away_player_X7'
 'away_player_X8' 'away_player_X9' 'away_player_X10' 'away_player_X11'
 'home_player_Y1' 'home_player_Y2' 'home_player_Y3' 'home_player_Y4'
 'home_player_Y5' 'home_player_Y6' 'home_player_Y7' 'home_player_Y8'
 'home_player_Y9' 'home_player_Y10' 'home_player_Y11' 'away_player_Y1'
 'away_player_Y2' 'away_player_Y3' 'away_player_Y4' 'away_player_Y5'
 'away_player_Y6' 'away_player_Y7' 'away_player_Y8' 'away_player_Y9'
 'away_player_Y10' 'away_player_Y11' 'home_player_1' 'home_player_2'
 'home_player_3' 'home_player_4' 'home_player_5' 'home_player_6'
 'home_player_7' 'home_player_8' 'home_player_9' 'home_player_10'
 'home_player_11' 'away_player_1' 'away_player_2' 'away_player_3'
 'away_player_4' 'away_player_5' 'away_player_6' 'away_player_7'
 'away_player_8' 'away_player_9' 'away_player_10' 'away_player_11']
['team_fifa_api_id' 'team_api_id' 'buildUpPlaySpeedClass'
 'buildUpPlayDribblingClass' 'buildUpPlayPassingClass'
 'chanceCreationPassingClass' 'chanceCreationCrossingClass'
 'chanceCreationShootingClass' 'defencePressureClass'
 'defenceTeamWidthClass' 'defenceDefenderLineClass_Cover'
 'defenceDefenderLineClass_Offside Trap' 'defenceAggressionClass_Contain'
 'defenceAggressionClass_Double' 'defenceAggressionClass_Press'
 'chanceCreationPositioningClass_Free Form'
 'chanceCreationPositioningClass_Organised'
 'buildUpPlayPositioningClass_Free Form'
 'buildUpPlayPositioningClass_Organised']

In [561]:
features_w_ta = features.merge(team_att_features,left_on = 'home_team_api_id',right_on = 'team_api_id')   #Features with team attributes

In [567]:
from sklearn.model_selection import TimeSeriesSplit, train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE

X_train, X_test, y_train, y_test = train_test_split(features_w_ta, target,test_size = 0.2, shuffle=True, random_state=42,stratify = target)

clf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
estimator = clf
selector = RFE(estimator, 10, step=1)
selector = selector.fit(X_train, y_train)
X_train.iloc[:, selector.support_].tail()

clf.fit(selector.transform(X_train), y_train)

score = clf.score(selector.transform(X_test), y_test)
y_pred = clf.predict(selector.transform(X_test))

print("Accuracy of prediction with Team attributes using Random Forest classifier:")
print(score)

Accuracy of prediction with Team attributes using Random Forest classifier:
0.39943342776203966

In [568]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

score = logreg.score(X_test, y_test)
print("Accuracy of prediction with Team attributes using Logistic Regression classifier:") 
print(score)

Accuracy of prediction with Team attributes using Logistic Regression classifier:
0.44192634560906513

C:\Users\Ayush\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ayush\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

In [569]:
from sklearn.naive_bayes import GaussianNB
gaussian = GaussianNB()
gaussian.fit(X_train,y_train)

score = gaussian.score(X_test,y_test)
print("Accuracy of prediction with Team attributes using Naive Bayes classifier:") 
print(score)

Accuracy of prediction with Team attributes using Naive Bayes classifier:
0.3597733711048159

In [570]:
from sklearn.model_selection import TimeSeriesSplit, train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE

X_train, X_test, y_train, y_test = train_test_split(features, target,test_size = 0.2, shuffle=True, random_state=42,stratify = target)

clf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
estimator = clf
selector = RFE(estimator, 10, step=1)
selector = selector.fit(X_train, y_train)
X_train.iloc[:, selector.support_].tail()

clf.fit(selector.transform(X_train), y_train)

score = clf.score(selector.transform(X_test), y_test)

print("Accuracy of prediction without Team attributes using Random Forest classifier:")
print(score)

team_att_features = team_attributes.drop(["id","buildUpPlaySpeed","buildUpPlayDribbling"
                                          ,"buildUpPlayPassing","chanceCreationPassing","chanceCreationCrossing",
                                          "chanceCreationShooting","defencePressure","defenceAggression","defenceTeamWidth"],axis=1)

Accuracy of prediction without Team attributes using Random Forest classifier:
0.45042492917847027

In [565]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)

score = logreg.score(X_test, y_test)
print("Accuracy of prediction without Team attributes using Logistic Regression classifier:") 
print(score)

Accuracy of prediction without Team attributes using Logistic Regression classifier:
0.43342776203966005

C:\Users\Ayush\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ayush\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

In [566]:
from sklearn.naive_bayes import GaussianNB
gaussian = GaussianNB()
gaussian.fit(X_train,y_train)

score = gaussian.score(X_test,y_test)
print("Accuracy of prediction without Team attributes using Naive Bayes classifier:") 
print(score)

Accuracy of prediction without Team attributes using Naive Bayes classifier:
0.42209631728045327